name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Ruby and Jekyll
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby-full build-essential zlib1g-dev
        gem install jekyll

    - name: Build Jekyll site
      run: jekyll build
      env:
        JEKYLL_ENV: production  # Set the Jekyll environment to production
      working-directory: ./docs  # Tell Jekyll to use the docs directory as the source

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_site  # Deploy the built site from the docs/_site directory
